import { chromium } from "@playwright/test";
import assert from "node:assert/strict";
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, permissions: ["clipboard-read", "clipboard-write"] });
const page = await context.newPage();
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
try {
 await page.goto(process.env.BASE_URL || "http://localhost:3001");
 const source = page.getByRole("textbox", { name: /Thai/ });
 await source.waitFor();
 await page.waitForTimeout(300);
 assert.equal(await source.evaluate(el => document.activeElement === el), true);
 assert.equal(await page.getByRole("button", { name: "Translate to English", exact: true }).isDisabled(), true);
 await page.getByRole("combobox", { name: "Translation mode", exact: true }).click();
 assert.equal(await page.getByRole("option").count(), 5);
 assert.equal(await page.locator('[role="option"][data-disabled]').count(), 4);
 assert.equal(await page.getByRole("option", { name: /Simple English/ }).getAttribute("aria-disabled"), "true");
 assert.equal(await page.getByRole("option").getByText("Soon", { exact: true }).count(), 4);
 await page.getByRole("option", { name: "Professional", exact: true }).click();
 assert.equal(await page.getByRole("combobox", { name: "Translation mode", exact: true }).textContent(), "Professional");
 await page.screenshot({ path: "/tmp/ai-translator-desktop.png", fullPage: true });
 await source.fill("เครื่องจักรมีปัญหา ช่างกำลังตรวจสอบ");
 await source.press("Control+Enter");
 await page.getByRole("button", { name: "Regenerate translation", exact: true }).locator("svg.animate-spin").waitFor();
 await page.getByText("Translation completed", { exact: true }).waitFor();
 await page.getByRole("button", { name: "Regenerate translation", exact: true }).locator("svg.animate-spin").waitFor({ state: "detached" });
 const expected = "The machine is currently experiencing an issue, and the technician is investigating the problem.";
 assert.equal(await page.locator('[aria-live="polite"] p').first().textContent(), expected);
 const copyIconButton = page.getByRole("button", { name: "Copy translation", exact: true });
 await copyIconButton.click();
 assert.equal(await page.evaluate(() => navigator.clipboard.readText()), expected);
 await copyIconButton.locator("[data-done]").waitFor();
 await copyIconButton.locator("[data-done]").waitFor({ state: "detached" });
 const copyTextButton = page.locator('div[aria-live="polite"]').getByRole("button", { name: "Copy", exact: true });
 await copyTextButton.click();
 await page.locator('div[aria-live="polite"]').getByRole("button", { name: "Copied", exact: true }).locator("[data-done]").waitFor();
 await copyTextButton.waitFor();
 await source.fill("วันนี้ production line หยุดประมาณ 30 นาที");
 await source.press("Meta+Enter");
 await page.waitForFunction(() => JSON.parse(localStorage.getItem("ai-translator-history")).length === 2);
 await page.reload();
 await source.waitFor();
 assert.equal(await page.getByRole("button", { name: "Open settings" }).count(), 0);
 await source.fill("วันนี้ production line หยุดประมาณ 30 นาที");
 await page.getByRole("button", { name: "Translate to English", exact: true }).click();
 const translated = "The production line was stopped for approximately 30 minutes today.";
 await page.getByText(translated, { exact: true }).waitFor();
 await page.waitForFunction(() => !document.querySelector('div[aria-busy="true"]'));
 assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem("ai-translator-history")).length), 3);
 assert.equal(await page.getByText("Refine your result").count(), 0);
 assert.equal(await page.getByRole("button", { name: "Make Shorter" }).count(), 0);
 const thaiSource = await source.inputValue();
 const swapInput = page.locator("#source-text");
 await page.getByRole("button", { name: "Swap languages" }).click();
 assert.equal(await swapInput.inputValue(), translated);
 assert.equal(await page.locator('[aria-live="polite"] p[lang="th"]').textContent(), thaiSource);
 await page.getByRole("button", { name: "Translate to Thai", exact: true }).waitFor();
 await page.getByRole("button", { name: "Swap languages" }).click();
 assert.equal(await swapInput.inputValue(), thaiSource);
 assert.equal(await page.locator('[aria-live="polite"] p[lang="en"]').textContent(), translated);
 const regenerateButton = page.getByRole("button", { name: "Regenerate translation", exact: true });
 await regenerateButton.click();
 await regenerateButton.locator("svg.animate-spin").waitFor();
 await page.waitForFunction(() => !document.querySelector('div[aria-busy="true"]'));
 await regenerateButton.locator("svg.animate-spin").waitFor({ state: "detached" });
 const pastedText = "วันนี้ production line หยุดประมาณ 30 นาที";
 await page.evaluate(text => navigator.clipboard.writeText(text), pastedText);
 await page.getByRole("button", { name: "Paste", exact: true }).click();
 assert.equal(await swapInput.inputValue(), pastedText);
 await page.getByRole("button", { name: "Pasted", exact: true }).locator("[data-done]").waitFor();
 const clearButton = page.getByRole("button", { name: "Clear input", exact: true });
 await clearButton.click();
 assert.equal(await swapInput.inputValue(), "");
 await clearButton.locator("[data-done]").waitFor();
 await clearButton.locator("[data-done]").waitFor({ state: "detached" });
 assert.equal(await clearButton.isDisabled(), true);

 for (const width of [768, 390, 320]) {
  await page.setViewportSize({ width, height: 900 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, "No overflow at " + width);
 }
 await page.setViewportSize({ width: 390, height: 844 });
 await page.evaluate(() => window.scrollTo(0, 0));
 await page.screenshot({ path: "/tmp/ai-translator-mobile.png", fullPage: true });
 await page.getByRole("button", { name: "Swap languages" }).click();
 await page.getByRole("button", { name: "Translate to Thai", exact: true }).waitFor();
 await page.reload();
 await page.getByRole("button", { name: "Translate to Thai", exact: true }).waitFor();
 assert.equal(await page.locator("#source-text").getAttribute("lang"), "en");
 await page.evaluate(() => localStorage.setItem("ai-translator-direction", JSON.stringify("fr-de")));
 await page.reload();
 await page.getByRole("button", { name: "Translate to English", exact: true }).waitFor();
 assert.equal(await page.locator("#source-text").getAttribute("lang"), "th");
 assert.deepEqual(errors, []);
 console.log("PASS: shortcuts, translation, clipboard, history, mode selection, no refine bar, button feedback, two-way swap, remembered direction, no settings entry, mobile/tablet overflow, and runtime errors.");
} finally { await browser.close(); }
