import { useLanguage } from "@/components/i18n/LanguageProvider";
import { ClipboardPaste, Trash2, CornerDownLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tooltip } from "@/components/ui/tooltip";
import { toast } from "sonner";
import { FeedbackIcon } from "@/components/ui/feedback-icon";
import { useFlash } from "@/hooks/useCopyFeedback";
export default function SourcePanel({ text, updateText, inputRef, language = "th" }) { const { t } = useLanguage();
 const isThai = language === "th";
 const pasted = useFlash();
 const cleared = useFlash();
 async function paste() { try { updateText(await navigator.clipboard.readText()); pasted.flash(); inputRef.current?.focus(); } catch { toast.error(t("Use Ctrl + V or Cmd + V to paste")); inputRef.current?.focus(); } }
 return <section className="flex min-w-0 flex-col md:min-h-0"><div className="mb-1 flex shrink-0 items-center justify-between"><label htmlFor="source-text" className="flex items-center gap-2.5 text-sm font-medium"><span className="rounded border bg-slate-50 px-1.5 py-0.5 text-[10px] font-normal text-slate-500">{language.toUpperCase()}</span>{t(isThai ? "Thai" : "English")}<span className="hidden text-xs font-light text-slate-500 sm:inline">{t("Source text")}</span></label><div className="flex"><Tooltip label={t("Paste text")}><Button variant="ghost" size="sm" onClick={paste}><FeedbackIcon icon={ClipboardPaste} done={pasted.active} /> <span>{t(pasted.active ? "Pasted" : "Paste")}</span></Button></Tooltip><Tooltip label={t("Clear input")}><Button variant="ghost" size="icon" aria-label={t("Clear input")} disabled={!text && !cleared.active} onClick={() => { updateText(""); cleared.flash(); inputRef.current?.focus(); }}><FeedbackIcon icon={Trash2} done={cleared.active} /></Button></Tooltip></div></div><div className="relative flex rounded-xl md:min-h-0 md:flex-1 border border-slate-200 bg-white transition-shadow focus-within:border-brand-300 focus-within:ring-2 focus-within:ring-brand-100"><textarea id="source-text" lang={language} ref={inputRef} autoFocus value={text} onChange={event => updateText(event.target.value)} onPaste={event => { const pasted = event.clipboardData.getData("text"); const el = event.currentTarget; if (text.length - (el.selectionEnd - el.selectionStart) + pasted.length > 5000) toast.error(t("Maximum 5000 characters allowed")); }} maxLength={5000} placeholder={t(isThai ? "Type the Thai text you want to translate..." : "Type the English text you want to translate...")} className="block h-[220px] min-h-0 w-full resize-none rounded-xl bg-transparent p-5 pb-12 text-base font-light leading-8 placeholder:text-slate-500 focus:outline-none md:h-full" /><span className="absolute bottom-4 right-4 text-[11px] font-light text-slate-500">{text.length.toLocaleString()} / 5000</span></div><p className="mt-1.5 flex shrink-0 items-center gap-1.5 text-[11px] font-light text-slate-500"><CornerDownLeft size={12} />{t("Press")} <kbd className="rounded border bg-slate-50 px-1.5 py-0.5 font-sans text-[10px] text-slate-500">Ctrl / ⌘ + Enter</kbd> {t("to translate")}</p></section>;
}
