import { useLanguage } from "@/components/i18n/LanguageProvider";
import { ArrowRight, Languages, Loader2, ArrowRightLeft } from "lucide-react";
import { Tooltip } from "@/components/ui/tooltip";
import SourcePanel from "./SourcePanel";
import OutputPanel from "./OutputPanel";
export default function TranslatorWorkspace({ translator, settings }) { const { t } = useLanguage();
 const { text, updateText, inputRef, result, loading, translate, sourceLanguage, targetLanguage, swapLanguages } = translator;
 return <div className="flex flex-col rounded-2xl md:min-h-0 md:flex-1 border bg-white shadow-[0_3px_16px_-8px_rgba(15,23,42,0.12)]"><div className="flex flex-col px-4 pb-3 pt-2 sm:px-5 md:min-h-0 md:flex-1"><div className="relative grid gap-4 md:min-h-0 md:flex-1 md:grid-cols-2 md:gap-16"><SourcePanel text={text} updateText={updateText} inputRef={inputRef} language={sourceLanguage} /><Tooltip label={t("Swap languages")}><button type="button" onClick={swapLanguages} disabled={loading} aria-label={t("Swap languages")} className="z-10 mx-auto flex size-9 items-center justify-center self-center rounded-full border bg-white text-slate-500 shadow-sm transition-colors hover:border-brand-200 hover:bg-brand-50 hover:text-brand-700 disabled:cursor-not-allowed disabled:opacity-55 md:absolute md:left-1/2 md:top-1/2 md:-translate-x-1/2 md:-translate-y-1/2"><ArrowRightLeft size={15} /></button></Tooltip><OutputPanel result={result} loading={loading} regenerate={translate} showTime={settings.processingTime} canTranslate={!!text.trim()} language={targetLanguage} /></div><div className="mt-3 flex shrink-0 flex-col items-center gap-1.5"><button onClick={translate} disabled={loading || !text.trim()} className="flex h-[50px] w-full items-center justify-center gap-2.5 rounded-xl bg-brand-500 px-6 text-sm text-white shadow-[0_3px_8px_-3px_#8dc63f60] transition-colors hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-55 sm:w-[250px]">{loading ? <Loader2 className="size-4 animate-spin" /> : <Languages className="size-[18px]" />}{t(loading ? "Translating..." : targetLanguage === "th" ? "Translate to Thai" : "Translate to English")}{!loading && <ArrowRight size={16} className="ml-2 opacity-70" />}</button></div></div></div>;
}
