import { useLanguage } from "@/components/i18n/LanguageProvider";
import { Settings2, ShieldCheck, Server, SlidersHorizontal } from "lucide-react";
import { Sheet, SheetContent, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Switch } from "@/components/ui/switch";
import { Select } from "@/components/ui/select";
import { modes } from "@/data/terminology";
export default function SettingsSheet({ open, onOpenChange, settings, update }) { const { t } = useLanguage();
 return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent><span className="mb-5 mt-3 flex size-11 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><Settings2 size={22} /></span><SheetTitle className="text-xl font-medium">{t("Translator Settings")}</SheetTitle><SheetDescription className="mt-1 text-sm font-light text-slate-500">{t("Make this workspace work for you.")}</SheetDescription><div className="mt-8"><label htmlFor="default-mode" className="mb-3 block text-sm">{t("Default Translation Mode")}</label><Select id="default-mode" value={settings.defaultMode} onValueChange={value => update("defaultMode", value)} options={modes.map(item => ({ ...item, label: t(item.label) }))} /></div><div className="my-7 border-t pt-6"><h3 className="mb-3 flex items-center gap-2 text-sm font-medium"><SlidersHorizontal size={15} />{t("AI Preferences")}</h3>{[{ key: "terminology", label: "Use company terminology" }, { key: "autoCopy", label: "Automatically copy translation" }, { key: "saveHistory", label: "Save translation history" }, { key: "processingTime", label: "Show processing time" }].map(item => <div key={item.key} className="flex min-h-14 items-center justify-between gap-4"><label htmlFor={item.key} className="text-[13px] font-light text-slate-600">{t(item.label)}</label><Switch id={item.key} checked={settings[item.key]} onCheckedChange={value => update(item.key, value)} /></div>)}</div><ServerStatusCard /><div className="mt-5 rounded-xl border border-brand-100 bg-brand-50/50 p-4"><h3 className="flex items-center gap-2 text-sm text-brand-800"><ShieldCheck size={16} />{t("Privacy")}</h3><p className="mt-2 text-xs font-light leading-6 text-slate-500">{t("Translation requests are processed through the company's internal AI infrastructure.")}</p><p className="mt-2 text-[11px] font-light leading-5 text-slate-500">{t("Preview mode: translations are simulated on this device. No text is sent to a server.")}</p></div></SheetContent></Sheet>;
}
function ServerStatusCard() { const { t } = useLanguage(); return <div className="rounded-xl border bg-slate-50/60 p-4"><h3 className="flex items-center gap-2 text-sm font-medium"><Server size={16} className="text-slate-500" />{t("Local AI Server")}<span className="ml-auto flex items-center gap-1.5 text-[10px] font-normal text-emerald-600"><span className="size-1.5 rounded-full bg-emerald-500" />{t("Connected")}</span></h3><dl className="mt-4 space-y-2.5">{[["Model", "gpt-oss-20b"], ["Provider", "Local AI"], ["Endpoint", "Internal API"], ["Deployment", "On-Premise"]].map(([label, value]) => <div key={label} className="flex justify-between text-xs"><dt className="font-light text-slate-500">{t(label)}</dt><dd className="text-slate-600">{t(value)}</dd></div>)}</dl><p className="mt-4 border-t pt-3 text-[10px] text-slate-500">{t("Simulated status · Backend integration ready")}</p></div>; }
